services:
  gamdl-aio:
    build:
      context: .
      args:
        TARGET_ARCH: arm64-v8a
        RUNTIME_PLATFORM: linux/arm64
    container_name: gamdl-aio
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
