<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>allstarr</RootNamespace>
        <Version>1.0.0</Version>
        <AssemblyVersion>1.0.0.0</AssemblyVersion>
        <FileVersion>1.0.0.0</FileVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
        <PackageReference Include="Cronos" Version="0.11.1" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.4" />
        <PackageReference Include="Otp.NET" Version="1.4.1" />
        <PackageReference Include="StackExchange.Redis" Version="2.8.16" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.4" />
        <PackageReference Include="TagLibSharp" Version="2.3.0" />
    </ItemGroup>

</Project>
