// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using allstarr.Core.Storage;

#nullable disable

namespace allstarr.Core.Storage.Migrations
{
    [DbContext(typeof(AllstarrDbContext))]
    [Migration("20260710153415_ProviderHealthRollups")]
    partial class ProviderHealthRollups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("allstarr.Core.Storage.AuditEventRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<Guid?>("ActorUserId");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<long>("CreatedAt");

                    b.Property<string>("DetailsJson")
                        .IsRequired();

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<Guid?>("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("allstarr.Core.Storage.BackendIdentityRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("BackendInstanceId")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("BackendType")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<long>("CreatedAt");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200);

                    b.Property<long>("LastSeenAt");

                    b.Property<string>("PrincipalId")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<Guid>("TenantId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "UserId");

                    b.HasIndex("BackendType", "BackendInstanceId", "PrincipalId")
                        .IsUnique();

                    b.ToTable("backend_identities", (string)null);
                });

            modelBuilder.Entity("allstarr.Core.Storage.BackupRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("ApplicationVersion")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("ArtifactPath")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<long>("CreatedAt");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<long?>("VerifiedAt");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("backups", (string)null);
                });

            modelBuilder.Entity("allstarr.Core.Storage.DurableJobRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<int>("AttemptCount");

                    b.Property<long>("AvailableAt");

                    b.Property<long?>("CancellationRequestedAt");

                    b.Property<long?>("CompletedAt");

                    b.Property<long>("CreatedAt");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(100);

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(1000);

                    b.Property<long?>("LeaseExpiresAt");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(200);

                    b.Property<int>("MaxAttempts");

                    b.Property<Guid?>("OwnerUserId");

                    b.Property<string>("PayloadJson")
                        .IsRequired();

                    b.Property<int>("Priority");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken();

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<long?>("StartedAt");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<Guid?>("TenantId");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<long>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("TenantId");

                    b.HasIndex("ScopeKey", "Type", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("State", "AvailableAt", "Priority");

                    b.ToTable("durable_jobs", (string)null);
                });

            modelBuilder.Entity("allstarr.Core.Storage.JobAttemptRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<int>("AttemptNumber");

                    b.Property<long?>("CompletedAt");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100);

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000);

                    b.Property<Guid>("JobId");

                    b.Property<string>("Outcome")
                        .HasMaxLength(50);

                    b.Property<long>("StartedAt");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("JobId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("job_attempts", (string)null);
                });

            modelBuilder.Entity("allstarr.Core.Storage.OutboxMessageRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<int>("AttemptCount");

                    b.Property<long>("AvailableAt");

                    b.Property<long>("CreatedAt");

                    b.Property<long?>("DeliveredAt");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(100);

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(1000);

                    b.Property<long?>("LeaseExpiresAt");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(200);

                    b.Property<string>("PayloadJson")
                        .IsRequired();

                    b.Property<long>("Revision")
                        .IsConcurrencyToken();

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<Guid?>("TenantId");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<long>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("State", "AvailableAt");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("allstarr.Core.Storage.PlatformUserRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<long>("CreatedAt");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<Guid>("TenantId");

                    b.Property<long>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Id")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("allstarr.Core.Storage.ProviderAccountRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<long>("CreatedAt");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<bool>("Enabled");

                    b.Property<string>("LibraryScopeId")
                        .HasMaxLength(300);

                    b.Property<Guid?>("OwnerUserId");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<long>("Revision")
                        .IsConcurrencyToken();

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<Guid?>("SecretReferenceId");

                    b.Property<Guid?>("TenantId");

                    b.Property<long>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("SecretReferenceId");

                    b.HasIndex("TenantId");

                    b.HasIndex("ProviderId", "TenantId", "OwnerUserId");

                    b.ToTable("provider_accounts", (string)null);
                });

            modelBuilder.Entity("allstarr.Core.Storage.ProviderCircuitRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("ConsecutiveFailures");

                    b.Property<long?>("OpenedAt");

                    b.Property<Guid>("ProviderAccountId");

                    b.Property<long?>("RetryAfter");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken();

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<long>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ProviderAccountId", "Capability")
                        .IsUnique();

                    b.ToTable("provider_circuits", (string)null);
                });

            modelBuilder.Entity("allstarr.Core.Storage.ProviderHealthRollupRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("FailureCount");

                    b.Property<string>("LastFailureCode")
                        .HasMaxLength(100);

                    b.Property<string>("LastState")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<long?>("P50LatencyMilliseconds");

                    b.Property<long?>("P95LatencyMilliseconds");

                    b.Property<Guid>("ProviderAccountId");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken();

                    b.Property<int>("SampleCount");

                    b.Property<int>("SuccessCount");

                    b.Property<double>("SuccessRate");

                    b.Property<Guid?>("TenantId");

                    b.Property<long>("UpdatedAt");

                    b.Property<long>("WindowEnd");

                    b.Property<long>("WindowStart");

                    b.HasKey("Id");

                    b.HasIndex("WindowEnd")
                        .HasDatabaseName("IX_provider_health_rollup_window_end");

                    b.HasIndex("ProviderAccountId", "Capability", "WindowStart")
                        .IsUnique()
                        .HasDatabaseName("IX_provider_health_rollup_account_capability_window");

                    b.ToTable("provider_health_rollups", (string)null);
                });

            modelBuilder.Entity("allstarr.Core.Storage.ProviderHealthSampleRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<long>("ExpiresAt");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100);

                    b.Property<long?>("LatencyMilliseconds");

                    b.Property<long>("ObservedAt");

                    b.Property<Guid>("ProviderAccountId");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<Guid?>("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("ProviderAccountId", "Capability", "ObservedAt")
                        .HasDatabaseName("IX_provider_health_account_capability_observed");

                    b.ToTable("provider_health_samples", (string)null);
                });

            modelBuilder.Entity("allstarr.Core.Storage.SecretReferenceRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<int>("ActiveVersion");

                    b.Property<long>("CreatedAt");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<long?>("RevokedAt");

                    b.Property<Guid?>("TenantId");

                    b.Property<long>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Purpose");

                    b.ToTable("secret_references", (string)null);
                });

            modelBuilder.Entity("allstarr.Core.Storage.SecretVersionRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<byte[]>("AuthenticationTag")
                        .IsRequired();

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired();

                    b.Property<long>("CreatedAt");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<byte[]>("Nonce")
                        .IsRequired();

                    b.Property<long?>("RetiredAt");

                    b.Property<Guid>("SecretReferenceId");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.HasIndex("SecretReferenceId", "Version")
                        .IsUnique();

                    b.ToTable("secret_versions", (string)null);
                });

            modelBuilder.Entity("allstarr.Core.Storage.TenantRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<long>("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("allstarr.Core.Storage.AuditEventRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.PlatformUserRecord", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("allstarr.Core.Storage.TenantRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("allstarr.Core.Storage.BackendIdentityRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.TenantRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("allstarr.Core.Storage.PlatformUserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("allstarr.Core.Storage.DurableJobRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.PlatformUserRecord", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("allstarr.Core.Storage.TenantRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("allstarr.Core.Storage.JobAttemptRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.DurableJobRecord", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("allstarr.Core.Storage.OutboxMessageRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.TenantRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("allstarr.Core.Storage.PlatformUserRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.TenantRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("allstarr.Core.Storage.ProviderAccountRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.PlatformUserRecord", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("allstarr.Core.Storage.SecretReferenceRecord", null)
                        .WithMany()
                        .HasForeignKey("SecretReferenceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("allstarr.Core.Storage.TenantRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("allstarr.Core.Storage.ProviderCircuitRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.ProviderAccountRecord", null)
                        .WithMany()
                        .HasForeignKey("ProviderAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("allstarr.Core.Storage.ProviderHealthRollupRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.ProviderAccountRecord", null)
                        .WithMany()
                        .HasForeignKey("ProviderAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("allstarr.Core.Storage.ProviderHealthSampleRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.ProviderAccountRecord", null)
                        .WithMany()
                        .HasForeignKey("ProviderAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("allstarr.Core.Storage.SecretReferenceRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.TenantRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("allstarr.Core.Storage.SecretVersionRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.SecretReferenceRecord", null)
                        .WithMany()
                        .HasForeignKey("SecretReferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
