// <auto-generated />
using System;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using allstarr.Core.Storage;

#nullable disable

namespace allstarr.Core.Storage.Migrations
{
    [DbContext(typeof(AllstarrDbContext))]
    [Migration("20260712015143_Phase4LibraryMatchingPlaylistFoundation")]
    partial class Phase4LibraryMatchingPlaylistFoundation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("allstarr.Core.Storage.AuditEventRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<Guid?>("ActorUserId");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<long>("CreatedAt");

                    b.Property<string>("DetailsJson")
                        .IsRequired();

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<Guid?>("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("allstarr.Core.Storage.BackendIdentityRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("BackendInstanceId")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("BackendType")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<long>("CreatedAt");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200);

                    b.Property<long>("LastSeenAt");

                    b.Property<string>("PrincipalId")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<Guid>("TenantId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "UserId");

                    b.HasIndex("BackendType", "BackendInstanceId", "PrincipalId")
                        .IsUnique();

                    b.ToTable("backend_identities", (string)null);
                });

            modelBuilder.Entity("allstarr.Core.Storage.BackupRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("ApplicationVersion")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("ArtifactPath")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<long>("CreatedAt");

                    b.Property<string>("RestoreStatus")
                        .HasMaxLength(50);

                    b.Property<long?>("RestoreVerifiedAt");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<long?>("VerifiedAt");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("backups", (string)null);
                });

            modelBuilder.Entity("allstarr.Core.Storage.CanonicalRecordingRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<long>("CreatedAt");

                    b.Property<Guid>("CreatedByUserId");

                    b.Property<string>("Isrc")
                        .HasMaxLength(32);

                    b.Property<string>("MusicBrainzRecordingId")
                        .HasMaxLength(100);

                    b.Property<long>("Revision")
                        .IsConcurrencyToken();

                    b.Property<Guid>("TenantId");

                    b.Property<long>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CreatedByUserId");

                    b.HasIndex("TenantId", "Isrc")
                        .IsUnique();

                    b.HasIndex("TenantId", "MusicBrainzRecordingId")
                        .IsUnique();

                    b.ToTable("canonical_recordings", (string)null);
                });

            modelBuilder.Entity("allstarr.Core.Storage.DurableJobRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<int>("AttemptCount");

                    b.Property<long>("AvailableAt");

                    b.Property<long?>("CancellationRequestedAt");

                    b.Property<long?>("CompletedAt");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<long>("CreatedAt");

                    b.Property<int>("DeferralCount");

                    b.Property<int>("FailureCount");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(100);

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(1000);

                    b.Property<long?>("LeaseExpiresAt");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(200);

                    b.Property<string>("LibraryScopeId")
                        .HasMaxLength(300);

                    b.Property<int>("MaxAttempts");

                    b.Property<int>("MaxDeferrals");

                    b.Property<Guid?>("OwnerUserId");

                    b.Property<string>("PayloadJson")
                        .IsRequired();

                    b.Property<string>("PolicySnapshotJson")
                        .IsRequired();

                    b.Property<int>("Priority");

                    b.Property<Guid?>("ProviderAccountId");

                    b.Property<string>("ProviderCapability")
                        .HasMaxLength(100);

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<long>("Revision")
                        .IsConcurrencyToken();

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<long?>("StartedAt");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<Guid?>("TenantId");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<long>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("ProviderAccountId");

                    b.HasIndex("TenantId");

                    b.HasIndex("ScopeKey", "Type", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("State", "AvailableAt", "Priority");

                    b.ToTable("durable_jobs", (string)null);
                });

            modelBuilder.Entity("allstarr.Core.Storage.ExternalMetadataSnapshotRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("BackendInstanceId")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("BackendPrincipalId")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("ExternalIdHash")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("LibraryScopeId")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<Guid>("OwnerUserId");

                    b.Property<string>("PayloadJson")
                        .IsRequired();

                    b.Property<string>("PayloadSha256")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<Guid>("ProviderAccountId");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("ProviderRevision")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<Guid?>("ProviderTrackIdentityId");

                    b.Property<string>("ResourceKind")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<long>("RetrievedAt");

                    b.Property<int>("SnapshotVersion");

                    b.Property<Guid?>("SourceJobId");

                    b.Property<Guid>("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("ProviderTrackIdentityId");

                    b.HasIndex("SourceJobId");

                    b.HasIndex("ProviderAccountId", "ProviderId");

                    b.HasIndex("TenantId", "OwnerUserId");

                    b.HasIndex("TenantId", "ProviderAccountId", "ResourceKind", "ExternalIdHash", "SnapshotVersion")
                        .IsUnique()
                        .HasDatabaseName("IX_external_snapshot_version");

                    b.ToTable("external_metadata_snapshots", null, t =>
                        {
                            t.HasCheckConstraint("CK_external_snapshots_external_hash", "length(\"ExternalIdHash\") = 64");

                            t.HasCheckConstraint("CK_external_snapshots_payload_hash", "length(\"PayloadSha256\") = 64");

                            t.HasCheckConstraint("CK_external_snapshots_version", "\"SnapshotVersion\" > 0");
                        });
                });

            modelBuilder.Entity("allstarr.Core.Storage.JobAttemptRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<int>("AttemptNumber");

                    b.Property<long?>("CompletedAt");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100);

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000);

                    b.Property<Guid>("JobId");

                    b.Property<string>("Outcome")
                        .HasMaxLength(50);

                    b.Property<long>("StartedAt");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("JobId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("job_attempts", (string)null);
                });

            modelBuilder.Entity("allstarr.Core.Storage.JobScheduleRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<long>("CreatedAt");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<bool>("Enabled");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("LibraryScopeId")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<string>("MisfirePolicy")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<long?>("NextRunAt");

                    b.Property<string>("OverlapPolicy")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<Guid>("OwnerUserId");

                    b.Property<string>("RetryPolicyJson")
                        .IsRequired();

                    b.Property<long>("Revision")
                        .IsConcurrencyToken();

                    b.Property<Guid>("TenantId");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<long>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Enabled", "NextRunAt");

                    b.HasIndex("TenantId", "OwnerUserId");

                    b.ToTable("job_schedules", (string)null);
                });

            modelBuilder.Entity("allstarr.Core.Storage.LibraryTrackRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<int?>("AcceptedDecisionVersion");

                    b.Property<string>("Album")
                        .HasMaxLength(500);

                    b.Property<string>("AlbumArtist")
                        .HasMaxLength(500);

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<Guid>("BackendIdentityId");

                    b.Property<string>("BackendInstanceId")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("BackendItemId")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<Guid?>("CanonicalRecordingId");

                    b.Property<string>("CoverArtReference")
                        .HasMaxLength(1000);

                    b.Property<long>("DurationMilliseconds");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<long>("IndexedAt");

                    b.Property<string>("Isrc")
                        .HasMaxLength(32);

                    b.Property<string>("LibraryScopeId")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<string>("MusicBrainzArtistId")
                        .HasMaxLength(100);

                    b.Property<string>("MusicBrainzRecordingId")
                        .HasMaxLength(100);

                    b.Property<string>("MusicBrainzReleaseId")
                        .HasMaxLength(100);

                    b.Property<Guid>("OwnerUserId");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("ProviderIdsJson")
                        .IsRequired();

                    b.Property<long>("Revision")
                        .IsConcurrencyToken();

                    b.Property<long>("SourceModifiedAt");

                    b.Property<Guid>("TenantId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<long>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("BackendIdentityId");

                    b.HasIndex("TenantId", "CanonicalRecordingId");

                    b.HasIndex("TenantId", "OwnerUserId", "LibraryScopeId", "Isrc")
                        .HasDatabaseName("IX_library_track_scoped_isrc");

                    b.HasIndex("TenantId", "OwnerUserId", "LibraryScopeId", "MusicBrainzRecordingId")
                        .HasDatabaseName("IX_library_track_scoped_musicbrainz");

                    b.HasIndex("TenantId", "OwnerUserId", "LibraryScopeId", "BackendInstanceId", "BackendItemId")
                        .IsUnique()
                        .HasDatabaseName("IX_library_track_backend_item");

                    b.ToTable("library_tracks", null, t =>
                        {
                            t.HasCheckConstraint("CK_library_tracks_decision_version", "\"AcceptedDecisionVersion\" IS NULL OR \"AcceptedDecisionVersion\" > 0");

                            t.HasCheckConstraint("CK_library_tracks_duration", "\"DurationMilliseconds\" >= 0");

                            t.HasCheckConstraint("CK_library_tracks_stable_artwork", "\"CoverArtReference\" IS NULL OR \"CoverArtReference\" NOT LIKE '%://%'");
                        });
                });

            modelBuilder.Entity("allstarr.Core.Storage.ManualTrackOverrideRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<long>("CreatedAt");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<int>("DecisionVersion");

                    b.Property<Guid>("ExternalSnapshotId");

                    b.Property<string>("LibraryScopeId")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<Guid?>("LibraryTrackId");

                    b.Property<Guid>("OwnerUserId");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<long>("Revision")
                        .IsConcurrencyToken();

                    b.Property<long?>("RevokedAt");

                    b.Property<Guid>("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ExternalSnapshotId");

                    b.HasIndex("TenantId", "LibraryTrackId");

                    b.HasIndex("TenantId", "OwnerUserId", "LibraryScopeId", "ExternalSnapshotId")
                        .IsUnique()
                        .HasDatabaseName("IX_manual_track_override_active")
                        .HasFilter("\"RevokedAt\" IS NULL");

                    b.ToTable("manual_track_overrides", null, t =>
                        {
                            t.HasCheckConstraint("CK_manual_overrides_shape", "(\"Decision\" = 'Pin' AND \"LibraryTrackId\" IS NOT NULL) OR (\"Decision\" = 'Reject' AND \"LibraryTrackId\" IS NULL)");

                            t.HasCheckConstraint("CK_manual_overrides_version", "\"DecisionVersion\" > 0");
                        });
                });

            modelBuilder.Entity("allstarr.Core.Storage.OutboxMessageRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<int>("AttemptCount");

                    b.Property<long>("AvailableAt");

                    b.Property<long>("CreatedAt");

                    b.Property<long?>("DeliveredAt");

                    b.Property<long?>("FailedAt");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(100);

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(1000);

                    b.Property<long?>("LeaseExpiresAt");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(200);

                    b.Property<int>("MaxAttempts");

                    b.Property<string>("PayloadJson")
                        .IsRequired();

                    b.Property<long>("Revision")
                        .IsConcurrencyToken();

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<Guid?>("TenantId");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<long>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("State", "AvailableAt");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("allstarr.Core.Storage.PlatformUserRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<long>("CreatedAt");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<Guid>("TenantId");

                    b.Property<long>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("allstarr.Core.Storage.PlaylistLinkRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<long>("CreatedAt");

                    b.Property<string>("LibraryScopeId")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<string>("MaterializationMode")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<bool>("MirrorStaleEntries");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<Guid>("OwnerUserId");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("PreserveManualEntries");

                    b.Property<Guid>("ProviderAccountId");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken();

                    b.Property<string>("RuleVersion")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<Guid?>("ScheduleId");

                    b.Property<string>("SourcePlaylistId")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("SourcePlaylistIdHash")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("SourceProviderId")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("SyncArtwork");

                    b.Property<bool>("SyncDescription");

                    b.Property<bool>("SyncName");

                    b.Property<string>("TargetBackendInstanceId")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("TargetPlaylistId")
                        .HasMaxLength(500);

                    b.Property<string>("TargetProtocol")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<Guid>("TenantId");

                    b.Property<long>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ProviderAccountId", "SourceProviderId");

                    b.HasIndex("TenantId", "ScheduleId");

                    b.HasIndex("TenantId", "OwnerUserId", "LibraryScopeId", "SourceProviderId", "ProviderAccountId", "SourcePlaylistIdHash", "TargetProtocol", "TargetBackendInstanceId")
                        .IsUnique()
                        .HasDatabaseName("IX_playlist_link_source_target");

                    b.ToTable("playlist_links", null, t =>
                        {
                            t.HasCheckConstraint("CK_playlist_links_source_hash", "length(\"SourcePlaylistIdHash\") = 64");
                        });
                });

            modelBuilder.Entity("allstarr.Core.Storage.PlaylistSourceEntryRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<Guid>("ExternalMetadataSnapshotId");

                    b.Property<Guid>("PlaylistSourceSnapshotId");

                    b.Property<string>("SourceEntryIdHash")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<int>("SourcePosition");

                    b.Property<Guid>("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ExternalMetadataSnapshotId");

                    b.HasIndex("TenantId", "PlaylistSourceSnapshotId", "SourcePosition")
                        .IsUnique()
                        .HasDatabaseName("IX_playlist_source_entry_position");

                    b.ToTable("playlist_source_entries", null, t =>
                        {
                            t.HasCheckConstraint("CK_playlist_source_entry_hash", "length(\"SourceEntryIdHash\") = 64");

                            t.HasCheckConstraint("CK_playlist_source_entry_position", "\"SourcePosition\" >= 0");
                        });
                });

            modelBuilder.Entity("allstarr.Core.Storage.PlaylistSourceSnapshotRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("ArtworkReferenceKey")
                        .HasMaxLength(1000);

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Description")
                        .HasMaxLength(4000);

                    b.Property<string>("ETag")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<Guid>("OwnerUserId");

                    b.Property<string>("PayloadSha256")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<Guid>("PlaylistLinkId");

                    b.Property<Guid>("ProviderAccountId");

                    b.Property<string>("ProviderRevision")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<long>("RetrievedAt");

                    b.Property<int>("SnapshotVersion");

                    b.Property<Guid?>("SourceJobId");

                    b.Property<Guid>("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("ProviderAccountId");

                    b.HasIndex("SourceJobId");

                    b.HasIndex("TenantId", "OwnerUserId");

                    b.HasIndex("TenantId", "PlaylistLinkId", "SnapshotVersion")
                        .IsUnique()
                        .HasDatabaseName("IX_playlist_snapshot_version");

                    b.ToTable("playlist_source_snapshots", null, t =>
                        {
                            t.HasCheckConstraint("CK_playlist_snapshots_payload_hash", "length(\"PayloadSha256\") = 64");

                            t.HasCheckConstraint("CK_playlist_snapshots_stable_artwork", "\"ArtworkReferenceKey\" IS NULL OR \"ArtworkReferenceKey\" NOT LIKE '%://%'");

                            t.HasCheckConstraint("CK_playlist_snapshots_version", "\"SnapshotVersion\" > 0");
                        });
                });

            modelBuilder.Entity("allstarr.Core.Storage.PlaylistSyncEntryResultRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("DetailsJson")
                        .IsRequired();

                    b.Property<Guid?>("LibraryTrackId");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("OutcomeCode")
                        .HasMaxLength(100);

                    b.Property<Guid>("PlaylistSourceEntryId");

                    b.Property<Guid>("PlaylistSyncRunId");

                    b.Property<int>("SourcePosition");

                    b.Property<int?>("TargetPosition");

                    b.Property<Guid>("TenantId");

                    b.Property<Guid?>("TrackMatchId");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "LibraryTrackId");

                    b.HasIndex("TenantId", "PlaylistSourceEntryId");

                    b.HasIndex("TenantId", "TrackMatchId");

                    b.HasIndex("TenantId", "PlaylistSyncRunId", "SourcePosition")
                        .IsUnique()
                        .HasDatabaseName("IX_playlist_result_run_position");

                    b.ToTable("playlist_sync_entry_results", null, t =>
                        {
                            t.HasCheckConstraint("CK_playlist_result_positions", "\"SourcePosition\" >= 0 AND (\"TargetPosition\" IS NULL OR \"TargetPosition\" >= 0)");
                        });
                });

            modelBuilder.Entity("allstarr.Core.Storage.PlaylistSyncRunRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<long?>("CompletedAt");

                    b.Property<string>("ConflictCode")
                        .HasMaxLength(100);

                    b.Property<long>("Generation");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<Guid?>("JobId");

                    b.Property<string>("MaterializationMode")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<Guid>("OwnerUserId");

                    b.Property<Guid>("PlaylistLinkId");

                    b.Property<Guid>("PlaylistSourceSnapshotId");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken();

                    b.Property<string>("RuleVersion")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<Guid?>("ScheduleId");

                    b.Property<long>("StartedAt");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("TargetRevisionAfter")
                        .HasMaxLength(500);

                    b.Property<string>("TargetRevisionBefore")
                        .HasMaxLength(500);

                    b.Property<Guid>("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("TenantId", "OwnerUserId");

                    b.HasIndex("TenantId", "PlaylistSourceSnapshotId");

                    b.HasIndex("TenantId", "ScheduleId");

                    b.HasIndex("TenantId", "PlaylistLinkId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("playlist_sync_runs", null, t =>
                        {
                            t.HasCheckConstraint("CK_playlist_sync_generation", "\"Generation\" > 0");
                        });
                });

            modelBuilder.Entity("allstarr.Core.Storage.PlaylistTargetMembershipRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<bool>("Active");

                    b.Property<long>("CreatedAt");

                    b.Property<Guid>("CreatedBySyncRunId");

                    b.Property<int>("LastKnownPosition");

                    b.Property<Guid>("LibraryTrackId");

                    b.Property<Guid>("PlaylistLinkId");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken();

                    b.Property<string>("TargetEntryId")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<Guid>("TenantId");

                    b.Property<long>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CreatedBySyncRunId");

                    b.HasIndex("TenantId", "LibraryTrackId");

                    b.HasIndex("TenantId", "PlaylistLinkId", "TargetEntryId")
                        .IsUnique()
                        .HasDatabaseName("IX_playlist_membership_target_entry");

                    b.HasIndex("TenantId", "PlaylistLinkId", "LibraryTrackId", "Active")
                        .HasDatabaseName("IX_playlist_membership_track_active");

                    b.ToTable("playlist_target_memberships", null, t =>
                        {
                            t.HasCheckConstraint("CK_playlist_membership_position", "\"LastKnownPosition\" >= 0");
                        });
                });

            modelBuilder.Entity("allstarr.Core.Storage.ProviderAccountRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<long>("CreatedAt");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<bool>("Enabled");

                    b.Property<string>("LibraryScopeId")
                        .HasMaxLength(300);

                    b.Property<Guid?>("OwnerUserId");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<long>("Revision")
                        .IsConcurrencyToken();

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<Guid?>("SecretReferenceId");

                    b.Property<Guid?>("TenantId");

                    b.Property<long>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("SecretReferenceId");

                    b.HasIndex("TenantId");

                    b.HasIndex("ProviderId", "TenantId", "OwnerUserId");

                    b.ToTable("provider_accounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_provider_accounts_scope_shape", "(\"Scope\" = 'Global' AND \"TenantId\" IS NULL AND \"OwnerUserId\" IS NULL AND \"LibraryScopeId\" IS NULL) OR (\"Scope\" = 'User' AND \"TenantId\" IS NOT NULL AND \"OwnerUserId\" IS NOT NULL AND \"LibraryScopeId\" IS NULL) OR (\"Scope\" = 'Library' AND \"TenantId\" IS NOT NULL AND \"OwnerUserId\" IS NULL AND \"LibraryScopeId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("allstarr.Core.Storage.ProviderCircuitRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("ConsecutiveFailures");

                    b.Property<long?>("OpenedAt");

                    b.Property<Guid>("ProviderAccountId");

                    b.Property<long?>("RetryAfter");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken();

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<long>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ProviderAccountId", "Capability")
                        .IsUnique();

                    b.ToTable("provider_circuits", (string)null);
                });

            modelBuilder.Entity("allstarr.Core.Storage.ProviderHealthRollupRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("FailureCount");

                    b.Property<string>("LastFailureCode")
                        .HasMaxLength(100);

                    b.Property<string>("LastState")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<long?>("P50LatencyMilliseconds");

                    b.Property<long?>("P95LatencyMilliseconds");

                    b.Property<Guid>("ProviderAccountId");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken();

                    b.Property<int>("SampleCount");

                    b.Property<int>("SuccessCount");

                    b.Property<double>("SuccessRate");

                    b.Property<Guid?>("TenantId");

                    b.Property<long>("UpdatedAt");

                    b.Property<long>("WindowEnd");

                    b.Property<long>("WindowStart");

                    b.HasKey("Id");

                    b.HasIndex("WindowEnd")
                        .HasDatabaseName("IX_provider_health_rollup_window_end");

                    b.HasIndex("ProviderAccountId", "Capability", "WindowStart")
                        .IsUnique()
                        .HasDatabaseName("IX_provider_health_rollup_account_capability_window");

                    b.ToTable("provider_health_rollups", (string)null);
                });

            modelBuilder.Entity("allstarr.Core.Storage.ProviderHealthSampleRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<long>("ExpiresAt");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100);

                    b.Property<long?>("LatencyMilliseconds");

                    b.Property<long>("ObservedAt");

                    b.Property<Guid>("ProviderAccountId");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<Guid?>("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("ProviderAccountId", "Capability", "ObservedAt")
                        .HasDatabaseName("IX_provider_health_account_capability_observed");

                    b.ToTable("provider_health_samples", (string)null);
                });

            modelBuilder.Entity("allstarr.Core.Storage.ProviderTrackIdentityRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<Guid>("CanonicalRecordingId");

                    b.Property<string>("CatalogNamespace")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<long>("CreatedAt");

                    b.Property<int>("DecisionVersion");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("ExternalIdHash")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<Guid?>("ProviderAccountId");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("ResourceKind")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<long>("Revision")
                        .IsConcurrencyToken();

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<Guid>("TenantId");

                    b.Property<long>("UpdatedAt");

                    b.Property<string>("Verification")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("VerificationMethod")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<long>("VerifiedAt");

                    b.HasKey("Id");

                    b.HasIndex("ProviderAccountId", "ProviderId");

                    b.HasIndex("TenantId", "CanonicalRecordingId");

                    b.HasIndex("TenantId", "ProviderId", "ResourceKind", "CatalogNamespace", "ExternalIdHash")
                        .IsUnique()
                        .HasDatabaseName("IX_provider_track_identity_catalog_exact")
                        .HasFilter("\"Scope\" = 'Catalog'");

                    b.HasIndex("TenantId", "ProviderId", "ResourceKind", "CatalogNamespace", "ProviderAccountId", "ExternalIdHash")
                        .IsUnique()
                        .HasDatabaseName("IX_provider_track_identity_account_exact")
                        .HasFilter("\"Scope\" = 'Account'");

                    b.ToTable("provider_track_identities", null, t =>
                        {
                            t.HasCheckConstraint("CK_provider_track_identities_decision_version", "\"DecisionVersion\" > 0");

                            t.HasCheckConstraint("CK_provider_track_identities_external_hash", "length(\"ExternalIdHash\") = 64");

                            t.HasCheckConstraint("CK_provider_track_identities_scope_shape", "(\"Scope\" = 'Catalog' AND \"ProviderAccountId\" IS NULL) OR (\"Scope\" = 'Account' AND \"ProviderAccountId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_provider_track_identities_track_only", "\"ResourceKind\" = 'Track'");

                            t.HasCheckConstraint("CK_provider_track_identities_verification", "\"Verification\" IN ('Verified', 'Pinned')");
                        });
                });

            modelBuilder.Entity("allstarr.Core.Storage.SecretReferenceRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<int>("ActiveVersion");

                    b.Property<long>("CreatedAt");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<long?>("RevokedAt");

                    b.Property<Guid?>("TenantId");

                    b.Property<long>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Purpose");

                    b.ToTable("secret_references", (string)null);
                });

            modelBuilder.Entity("allstarr.Core.Storage.SecretVersionRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<byte[]>("AuthenticationTag")
                        .IsRequired();

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired();

                    b.Property<long>("CreatedAt");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<byte[]>("Nonce")
                        .IsRequired();

                    b.Property<long?>("RetiredAt");

                    b.Property<Guid>("SecretReferenceId");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.HasIndex("SecretReferenceId", "Version")
                        .IsUnique();

                    b.ToTable("secret_versions", (string)null);
                });

            modelBuilder.Entity("allstarr.Core.Storage.TenantRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<long>("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("allstarr.Core.Storage.TrackMatchRecord", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("CandidateResultsJson")
                        .IsRequired();

                    b.Property<Guid?>("CanonicalRecordingId");

                    b.Property<double>("Confidence");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<long>("DecidedAt");

                    b.Property<int>("DecisionVersion");

                    b.Property<Guid>("ExternalSnapshotId");

                    b.Property<string>("LibraryScopeId")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<Guid?>("LibraryTrackId");

                    b.Property<Guid>("OwnerUserId");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("ReasonsJson")
                        .IsRequired();

                    b.Property<long>("Revision")
                        .IsConcurrencyToken();

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<Guid>("TenantId");

                    b.Property<double>("Threshold");

                    b.Property<string>("WarningsJson")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CanonicalRecordingId");

                    b.HasIndex("TenantId", "ExternalSnapshotId");

                    b.HasIndex("TenantId", "LibraryTrackId");

                    b.HasIndex("TenantId", "OwnerUserId", "LibraryScopeId", "ExternalSnapshotId", "DecisionVersion")
                        .IsUnique()
                        .HasDatabaseName("IX_track_match_scoped_decision");

                    b.ToTable("track_matches", null, t =>
                        {
                            t.HasCheckConstraint("CK_track_matches_confidence", "\"Confidence\" >= 0 AND \"Confidence\" <= 1 AND \"Threshold\" >= 0 AND \"Threshold\" <= 1");

                            t.HasCheckConstraint("CK_track_matches_selected_shape", "(\"State\" IN ('Accepted', 'Pinned') AND \"LibraryTrackId\" IS NOT NULL) OR (\"State\" IN ('Unresolved', 'Suggested', 'Rejected', 'Ambiguous') AND \"LibraryTrackId\" IS NULL)");

                            t.HasCheckConstraint("CK_track_matches_version", "\"DecisionVersion\" > 0");
                        });
                });

            modelBuilder.Entity("allstarr.Core.Storage.AuditEventRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.PlatformUserRecord", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("allstarr.Core.Storage.TenantRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("allstarr.Core.Storage.BackendIdentityRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.TenantRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("allstarr.Core.Storage.PlatformUserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("allstarr.Core.Storage.CanonicalRecordingRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.TenantRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("allstarr.Core.Storage.PlatformUserRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CreatedByUserId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("allstarr.Core.Storage.DurableJobRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.PlatformUserRecord", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("allstarr.Core.Storage.ProviderAccountRecord", null)
                        .WithMany()
                        .HasForeignKey("ProviderAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("allstarr.Core.Storage.TenantRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("allstarr.Core.Storage.ExternalMetadataSnapshotRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.ProviderTrackIdentityRecord", null)
                        .WithMany()
                        .HasForeignKey("ProviderTrackIdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_external_snapshot_provider_identity");

                    b.HasOne("allstarr.Core.Storage.DurableJobRecord", null)
                        .WithMany()
                        .HasForeignKey("SourceJobId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("allstarr.Core.Storage.ProviderAccountRecord", null)
                        .WithMany()
                        .HasForeignKey("ProviderAccountId", "ProviderId")
                        .HasPrincipalKey("Id", "ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_external_snapshot_provider_account");

                    b.HasOne("allstarr.Core.Storage.PlatformUserRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "OwnerUserId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ExternalMetadataSnapshot_PlatformUser");
                });

            modelBuilder.Entity("allstarr.Core.Storage.JobAttemptRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.DurableJobRecord", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("allstarr.Core.Storage.JobScheduleRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.PlatformUserRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "OwnerUserId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_JobSchedule_PlatformUser");
                });

            modelBuilder.Entity("allstarr.Core.Storage.LibraryTrackRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.BackendIdentityRecord", null)
                        .WithMany()
                        .HasForeignKey("BackendIdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("allstarr.Core.Storage.CanonicalRecordingRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CanonicalRecordingId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_library_track_canonical_recording");

                    b.HasOne("allstarr.Core.Storage.PlatformUserRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "OwnerUserId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_LibraryTrack_PlatformUser");
                });

            modelBuilder.Entity("allstarr.Core.Storage.ManualTrackOverrideRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.ExternalMetadataSnapshotRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ExternalSnapshotId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ManualTrackOverride_ExternalMetadataSnapshot");

                    b.HasOne("allstarr.Core.Storage.LibraryTrackRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "LibraryTrackId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ManualTrackOverride_LibraryTrack");

                    b.HasOne("allstarr.Core.Storage.PlatformUserRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "OwnerUserId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ManualTrackOverride_PlatformUser");
                });

            modelBuilder.Entity("allstarr.Core.Storage.OutboxMessageRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.TenantRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("allstarr.Core.Storage.PlatformUserRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.TenantRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("allstarr.Core.Storage.PlaylistLinkRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.ProviderAccountRecord", null)
                        .WithMany()
                        .HasForeignKey("ProviderAccountId", "SourceProviderId")
                        .HasPrincipalKey("Id", "ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_playlist_link_provider_account");

                    b.HasOne("allstarr.Core.Storage.PlatformUserRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "OwnerUserId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PlaylistLink_PlatformUser");

                    b.HasOne("allstarr.Core.Storage.JobScheduleRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ScheduleId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_PlaylistLink_JobSchedule");
                });

            modelBuilder.Entity("allstarr.Core.Storage.PlaylistSourceEntryRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.ExternalMetadataSnapshotRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ExternalMetadataSnapshotId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PlaylistSourceEntry_ExternalMetadataSnapshot");

                    b.HasOne("allstarr.Core.Storage.PlaylistSourceSnapshotRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PlaylistSourceSnapshotId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PlaylistSourceEntry_PlaylistSourceSnapshot");
                });

            modelBuilder.Entity("allstarr.Core.Storage.PlaylistSourceSnapshotRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.ProviderAccountRecord", null)
                        .WithMany()
                        .HasForeignKey("ProviderAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_playlist_snapshot_provider_account");

                    b.HasOne("allstarr.Core.Storage.DurableJobRecord", null)
                        .WithMany()
                        .HasForeignKey("SourceJobId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("allstarr.Core.Storage.PlatformUserRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "OwnerUserId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PlaylistSourceSnapshot_PlatformUser");

                    b.HasOne("allstarr.Core.Storage.PlaylistLinkRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PlaylistLinkId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PlaylistSourceSnapshot_PlaylistLink");
                });

            modelBuilder.Entity("allstarr.Core.Storage.PlaylistSyncEntryResultRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.LibraryTrackRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "LibraryTrackId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_PlaylistSyncEntryResult_LibraryTrack");

                    b.HasOne("allstarr.Core.Storage.PlaylistSourceEntryRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PlaylistSourceEntryId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PlaylistSyncEntryResult_PlaylistSourceEntry");

                    b.HasOne("allstarr.Core.Storage.PlaylistSyncRunRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PlaylistSyncRunId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PlaylistSyncEntryResult_PlaylistSyncRun");

                    b.HasOne("allstarr.Core.Storage.TrackMatchRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "TrackMatchId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_PlaylistSyncEntryResult_TrackMatch");
                });

            modelBuilder.Entity("allstarr.Core.Storage.PlaylistSyncRunRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.DurableJobRecord", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("allstarr.Core.Storage.PlatformUserRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "OwnerUserId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PlaylistSyncRun_PlatformUser");

                    b.HasOne("allstarr.Core.Storage.PlaylistLinkRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PlaylistLinkId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PlaylistSyncRun_PlaylistLink");

                    b.HasOne("allstarr.Core.Storage.PlaylistSourceSnapshotRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PlaylistSourceSnapshotId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PlaylistSyncRun_PlaylistSourceSnapshot");

                    b.HasOne("allstarr.Core.Storage.JobScheduleRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ScheduleId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_PlaylistSyncRun_JobSchedule");
                });

            modelBuilder.Entity("allstarr.Core.Storage.PlaylistTargetMembershipRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.PlaylistSyncRunRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CreatedBySyncRunId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PlaylistTargetMembership_PlaylistSyncRun");

                    b.HasOne("allstarr.Core.Storage.LibraryTrackRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "LibraryTrackId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PlaylistTargetMembership_LibraryTrack");

                    b.HasOne("allstarr.Core.Storage.PlaylistLinkRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PlaylistLinkId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PlaylistTargetMembership_PlaylistLink");
                });

            modelBuilder.Entity("allstarr.Core.Storage.ProviderAccountRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.PlatformUserRecord", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("allstarr.Core.Storage.SecretReferenceRecord", null)
                        .WithMany()
                        .HasForeignKey("SecretReferenceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("allstarr.Core.Storage.TenantRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("allstarr.Core.Storage.ProviderCircuitRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.ProviderAccountRecord", null)
                        .WithMany()
                        .HasForeignKey("ProviderAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("allstarr.Core.Storage.ProviderHealthRollupRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.ProviderAccountRecord", null)
                        .WithMany()
                        .HasForeignKey("ProviderAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("allstarr.Core.Storage.ProviderHealthSampleRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.ProviderAccountRecord", null)
                        .WithMany()
                        .HasForeignKey("ProviderAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("allstarr.Core.Storage.ProviderTrackIdentityRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.TenantRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("allstarr.Core.Storage.ProviderAccountRecord", null)
                        .WithMany()
                        .HasForeignKey("ProviderAccountId", "ProviderId")
                        .HasPrincipalKey("Id", "ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_track_identity_provider_account");

                    b.HasOne("allstarr.Core.Storage.CanonicalRecordingRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CanonicalRecordingId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_track_identity_canonical_recording");
                });

            modelBuilder.Entity("allstarr.Core.Storage.SecretReferenceRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.TenantRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("allstarr.Core.Storage.SecretVersionRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.SecretReferenceRecord", null)
                        .WithMany()
                        .HasForeignKey("SecretReferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("allstarr.Core.Storage.TrackMatchRecord", b =>
                {
                    b.HasOne("allstarr.Core.Storage.CanonicalRecordingRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CanonicalRecordingId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_TrackMatch_Canonicaling");

                    b.HasOne("allstarr.Core.Storage.ExternalMetadataSnapshotRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ExternalSnapshotId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TrackMatch_ExternalMetadataSnapshot");

                    b.HasOne("allstarr.Core.Storage.LibraryTrackRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "LibraryTrackId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_TrackMatch_LibraryTrack");

                    b.HasOne("allstarr.Core.Storage.PlatformUserRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "OwnerUserId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TrackMatch_PlatformUser");
                });
#pragma warning restore 612, 618
        }
    }
}
